/**
 * Canonical serialization and hashing for onchain commitments
 * Ensures policy hash generated by app and commitment stored by Cairo contract match deterministically
 * Do NOT hash arbitrary JSON in inconsistent property order
 */

import { hash } from "starknet";
import type { Hex } from "../types";
import type { AgentPolicy } from "../policy/model";

/**
 * Canonical policy serialization — deterministic, sorted keys, no floating point
 * Same policy always produces same commitment, changed policy → different hash
 */
export function canonicalPolicySerialize(policy: AgentPolicy): string[] {
  // Sort and encode fields deterministically
  // Order: agentId, owner, allowedAssets (sorted), maxTx, dailyLimit, approvedRecipients (sorted), threshold, allowedActions (sorted), paused
  const parts: string[] = [];

  parts.push(policy.agentId);
  parts.push(policy.owner.toLowerCase());

  // Sorted assets
  const sortedAssets = [...policy.allowedAssets].sort();
  parts.push(sortedAssets.join(","));

  parts.push(policy.maximumTransactionAmount.toString());
  parts.push(policy.dailySpendingLimit.toString());

  const sortedRecipients = [...policy.approvedRecipients].map((a) => a.toLowerCase()).sort();
  parts.push(sortedRecipients.join(","));

  parts.push(policy.approvalThreshold.toString());

  const sortedActions = [...policy.allowedActions].sort();
  parts.push(sortedActions.join(","));

  parts.push(policy.paused ? "1" : "0");

  return parts;
}

/**
 * Convert string to felt252 hex — simple encoding for hashing
 * For production, use proper Cairo encoding (e.g., starknet.js hash)
 */
function stringToFeltHex(str: string): bigint {
  // Simple: hash string to bigint via keccak or just encode as felt if short
  // For MVP, we use poseidonHashMany on array of felts derived from string bytes
  // This is a placeholder — real implementation would use starknet.js shortString or compute hash
  let hash = 0n;
  for (let i = 0; i < str.length; i++) {
    hash = (hash * 31n + BigInt(str.charCodeAt(i))) & ((1n << 251n) - 1n); // keep within felt range
  }
  return hash;
}

export function canonicalPolicyHash(policy: AgentPolicy): Hex {
  try {
    const serialized = canonicalPolicySerialize(policy);
    const felts = serialized.map((s) => stringToFeltHex(s));
    const hashStr = hash.computePoseidonHashOnElements(felts);
    return hashStr as Hex;
  } catch {
    const { poseidonish } = require("../hash");
    return poseidonish(policy) as Hex;
  }
}

/**
 * Canonical execution commitment — based only on non-sensitive deterministic metadata
 * Conceptually: agent, policy version, intent commitment, verdict, execution status, timestamp/nonce
 * Does NOT include private transaction details if they should not be publicly anchored
 */

export interface ExecutionCommitmentData {
  agentId: string;
  policyVersion: number;
  intentHash: Hex;
  verdict: number; // 0=APPROVE,1=REJECT,2=REQUIRE_USER_CONFIRMATION
  executionStatus: number; // 0=PROPOSED,1=POLICY_APPROVED,2=AWAITING_USER,3=EXECUTING,4=COMPLETED,5=BLOCKED,6=FAILED,7=CANCELLED
  timestamp: number;
  nonce?: number;
}

export function canonicalExecutionSerialize(data: ExecutionCommitmentData): bigint[] {
  return [
    stringToFeltHex(data.agentId),
    BigInt(data.policyVersion),
    BigInt(data.intentHash),
    BigInt(data.verdict),
    BigInt(data.executionStatus),
    BigInt(data.timestamp),
    BigInt(data.nonce ?? 0),
  ];
}

export function canonicalExecutionHash(data: ExecutionCommitmentData): Hex {
  try {
    const felts = canonicalExecutionSerialize(data);
    const hashStr = hash.computePoseidonHashOnElements(felts);
    return hashStr as Hex;
  } catch {
    const { poseidonish } = require("../hash");
    return poseidonish(data) as Hex;
  }
}

// Tests for hash consistency per TASK 14 and 15
export function testPolicyHashConsistency(): { samePolicySameHash: boolean; changedPolicyDifferentHash: boolean; differentVersionDifferentCommitment: boolean } {
  const basePolicy: AgentPolicy = {
    agentId: "holographic-treasury",
    owner: "0x04a7c1b8e93f25d60a1b7c2d3e4f5a6b7c8d9e0f",
    allowedAssets: ["USDC"],
    maximumTransactionAmount: 500 * 1_000_000,
    dailySpendingLimit: 5000 * 1_000_000,
    approvedRecipients: ["0x0512ff9a34cd7e21b8046f5c3d2a1e0b9c8d7e21f"],
    approvalThreshold: 250 * 1_000_000,
    allowedActions: ["transfer"],
    paused: false,
  };

  const samePolicy = { ...basePolicy };
  const changedPolicy = { ...basePolicy, maximumTransactionAmount: 600 * 1_000_000 };
  const differentVersionPolicy = { ...basePolicy, allowedAssets: ["USDC", "STRK"] };

  const hash1 = canonicalPolicyHash(basePolicy);
  const hashSame = canonicalPolicyHash(samePolicy);
  const hashChanged = canonicalPolicyHash(changedPolicy);
  const hashDifferentVersion = canonicalPolicyHash(differentVersionPolicy);

  return {
    samePolicySameHash: hash1 === hashSame,
    changedPolicyDifferentHash: hash1 !== hashChanged,
    differentVersionDifferentCommitment: hash1 !== hashDifferentVersion,
  };
}
